name: prop_env
channels:
  - defaults
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - ipython_genutils=0.2.0
  - jinja2=2.10.3
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libsodium=1.0.16
  - markupsafe=1.1.1
  - mistune=0.8.4
  - more-itertools=8.0.2
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.1
  - ncurses=6.1
  - openssl=1.1.1d
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.2
  - ptyprocess=0.6.0
  - pygments=2.5.2
  - python=3.7.6
  - pyzmq=18.1.0
  - readline=7.0
  - send2trash=1.5.0
  - setuptools=45.1.0
  - sqlite=3.30.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - altair==4.0.0
    - argh==0.26.2
    - astor==0.8.1
    - autopep8==1.4.4
    - base58==1.0.3
    - blinker==1.4
    - boto3==1.10.48
    - botocore==1.13.48
    - branca==0.3.1
    - chardet==3.0.4
    - click==7.0
    - click-plugins==1.1.1
    - cligj==0.5.0
    - cycler==0.10.0
    - docutils==0.15.2
    - enum-compat==0.0.3
    - fiona==1.8.13
    - folium==0.10.1
    - future==0.18.2
    - geographiclib==1.50
    - geopandas==0.6.2
    - geopy==1.20.0
    - idna==2.8
    - importlib-metadata==1.3.0
    - ipykernel==5.1.3
    - ipython==7.10.2
    - ipywidgets==7.5.1
    - jedi==0.15.1
    - jmespath==0.9.4
    - joblib==0.14.1
    - kiwisolver==1.1.0
    - matplotlib==3.1.2
    - munch==2.5.0
    - nbformat==4.4.0
    - notebook==6.0.2
    - numexpr==2.7.0
    - numpy==1.18.0
    - pandas==0.25.3
    - parso==0.5.2
    - pathtools==0.1.2
    - pexpect==4.7.0
    - pillow==7.0.0
    - protobuf==3.11.2
    - pycodestyle==2.5.0
    - pyparsing==2.4.6
    - pyproj==2.4.2.post1
    - pyrsistent==0.15.6
    - python-dateutil==2.8.0
    - pytz==2019.3
    - pyyaml==5.3
    - requests==2.22.0
    - s3transfer==0.2.1
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - seaborn==0.9.0
    - shapely==1.6.4.post2
    - six==1.13.0
    - streamlit==0.52.2
    - tables==3.6.1
    - toml==0.10.0
    - toolz==0.10.0
    - tornado==5.1.1
    - traittypes==0.2.1
    - tzlocal==2.0.0
    - urllib3==1.25.7
    - validators==0.14.1
    - watchdog==0.9.0
    - widgetsnbextension==3.5.1
    - xlrd==1.2.0
